rails-task-manager/config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

rails-task-manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-task-manager/app/models/task.rb
class Task < ApplicationRecord
end

rails-task-manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-task-manager/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @all_tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    Task.new(task_params).save
    redirect_to "/tasks"
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    Task.find(params[:id]).update(task_params)
    redirect_to "/tasks"
  end

  def destroy
    Task.find(params[:id]).destroy
    redirect_to "/tasks"
  end

  def task_params
    params.require(:task).permit(:name, :done)
  end

end

rails-task-manager/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-task-manager/app/helpers/tasks_helper.rb
module TasksHelper
end

rails-task-manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-task-manager/app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to("BACK TO LIST", tasks_path) %>

rails-task-manager/app/views/tasks/index.html.erb
<h1>LIST OF TASKS</h1>

<% @all_tasks.each do |i| %>
  <p><%= link_to("#{i.id} - #{i.name} - #{i.done ? '[X]' : '[ ]'}", task_path(i.id)) %></p>
<% end %>

<%= link_to("CREATE NEW", new_task_path) %>

rails-task-manager/app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to("BACK TO LIST", tasks_path) %>

rails-task-manager/app/views/tasks/show.html.erb
<p>ID: <%= @task.id %></p>
<p>NAME: <%= @task.name%></p>
<p>DONE: <%= @task.done ? "[X]" : "[ ]"%></p>

<%= link_to("DELETE", task_path(@task.id), method: :delete) %>
<%= link_to("UPDATE", edit_task_path(@task.id)) %>
<%= link_to("BACK TO LIST", tasks_path) %>
<%= link_to("MARK AS DONE", task_path(@task, task: {done: true}), method: :patch) %>